// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zseyroqnqsoaeaerobzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZXlyb3FucXNvYWVhZXJvYnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjEzNjEsImV4cCI6MjA2MDA5NzM2MX0._pH6B0smHTKrbyKFJH3BizIJl1zHAmB9ye74CcJxzow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);